[env]
TERM = "xterm-256color"

[shell]
program = "zellij"

[window]
padding.x = 5
padding.y = 5
dynamic_padding = false
decorations = "none"
opacity = 0.95

[keyboard]
bindings = [{ key = "F11", action = "ToggleFullscreen" }]
